[build]
  command = "npm run build --legacy-peer-deps"
  publish = "dist"
  functions = "netlify/functions"

[context.develop.environment]
  VITE_APP_CHAIN_ID = "97"
  VITE_APP_INFURA_ID = "9aa3d95b3bc440fa88ea12eaa4456161"
  VITE_APP_RPC = "https://data-seed-prebsc-1-s1.binance.org:8545"
  VITE_APP_GOOGLE_MAPS_API_KEY = "AIzaSyCLj_kYuJtEOn-7543AcyFSdaD0iqu6mWM"
  VITE_APP_S3_KEY_ID = "AKIARUVWW7KUX2M225HL"
  VITE_APP_S3_ACCESS_KEY = "lWDCfO+9Tqah0gw1cmqccwrazPYgK20WHR2g2r33"
  VITE_APP_S3_REGION = "us-east-1"
  VITE_APP_S3_BUCKET = "newagro-app"
  VITE_APP_ADMIN_ADDRESSES= "0x86b10920544a79A6Dcd26AB6BaF2dB1557c55fcD,0x7Cf5eAa44ED9FE43d64CB74f7a89BD78954E9ea6,0x6F19d7dB56E71858Cd72eda36D2d367bC0C9a9D7,0x2309dE234513b43e93D3bDB9CeAB97768af05938,0x279022813D38Fa33c1A4ACB8A2b9F6a5A71F6307,0xD7148Eb5a216e80d68BB5de3F357D1176e4E07f6"
  NETLIFY_USE_YARN = false

[context.app.environment]
  VITE_APP_CHAIN_ID = "56"
  VITE_APP_INFURA_ID = "9aa3d95b3bc440fa88ea12eaa4456161"
  VITE_APP_RPC = "https://bsc-dataseed1.ninicoin.io"
  VITE_APP_GOOGLE_MAPS_API_KEY = "AIzaSyCLj_kYuJtEOn-7543AcyFSdaD0iqu6mWM"
  VITE_APP_S3_KEY_ID = "AKIARUVWW7KUX2M225HL"
  VITE_APP_S3_ACCESS_KEY = "lWDCfO+9Tqah0gw1cmqccwrazPYgK20WHR2g2r33"
  VITE_APP_S3_REGION = "us-east-1"
  VITE_APP_S3_BUCKET = "newagro-app"
  VITE_APP_ADMIN_ADDRESSES= "0x86b10920544a79A6Dcd26AB6BaF2dB1557c55fcD,0x7Cf5eAa44ED9FE43d64CB74f7a89BD78954E9ea6,0x6F19d7dB56E71858Cd72eda36D2d367bC0C9a9D7,0x2309dE234513b43e93D3bDB9CeAB97768af05938,0x279022813D38Fa33c1A4ACB8A2b9F6a5A71F6307,0xD7148Eb5a216e80d68BB5de3F357D1176e4E07f6"
  NETLIFY_USE_YARN = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200