import contracts from "./contracts";
import { Ifo } from "./types";

const ifos: Ifo[] = [
  {
    id: "defilaunch",
    address: "0x848757F7b7C9Dd7F3dcDC125B0C5122b4571750f",
    isActive: false,
    name: "DefiLaunch",
    subTitle:
      "DefiLaunch is an incubator of high growth potencial DeFi projects that counts with a development, marketing, communication and security team to support and advice them on their way out to the market. It offers a unique and safe destination for both pre-sale investors and pre-launch projects. DeFiLaunch is the evolution of the DeFi Launchpad together with the best user experience.",
    description:
      "DefiLaunch is an incubator of high growth potencial DeFi projects that counts with a development, marketing, communication and security team to support and advice them on their way out to the market. It offers a unique and safe destination for both pre-sale investors and pre-launch projects. DeFiLaunch is the evolution of the DeFi Launchpad together with the best user experience.",
    launchDate: "November 1st",
    launchTime: "11PM UTC",
    saleAmount: "250,000 DLAUNCH",
    raiseAmount: "250,000 BUSD",
    cakeToBurn: "0",
    projectSiteUrl: "https://defilaunch.finance",
    currency: "BUSD",
    currencyAddress: contracts.busd[56],
    tokenDecimals: 18,
    tokenSymbol: "DLAUNCH",
    releaseBlockNumber: 5294924,
    campaignId: "007",
    twitterUrl: "https://twitter.com/defi_launch",
    telegramUrl: "https://t.me/DeFi_Launch",
    launchPrice: 1.1,
    audit: "/files/certik_audit.pdf",
    countdown: true,
  },
  {
    id: "bikini",
    address: "0xe015236b280883b9fe316636B753b3FdefD13A08",
    address1: "0xe015236b280883b9fe316636B753b3FdefD13A08",
    address2: "0xe015236b280883b9fe316636B753b3FdefD13A08",
    isActive: false,
    name: "Bikini Finance",
    subTitle:
      "Bikini Finance is focused on building an all in one DeFi ecosystem, featuring an Automated Market Market, high yield farming, yield aggregation and optimization, NFT marketplace and many more new developments to create a complete decentralized experience for investors.",
    description:
      "Bikini Finance is focused on building an all in one DeFi ecosystem, featuring an Automated Market Market, high yield farming, yield aggregation and optimization, NFT marketplace and many more new developments to create a complete decentralized experience for investors.",
    launchDate: "November 15th",
    launchTime: "11PM UTC",
    saleAmount: "50,000 BIKINI",
    raiseAmount: "200 WBNB",
    cakeToBurn: "0",
    projectSiteUrl: "",
    currency: "BUSD",
    currencyAddress: contracts.busd[56],
    tokenDecimals: 18,
    tokenSymbol: "BIKINI",
    releaseBlockNumber: 5294924,
    campaignId: "007",
    twitterUrl: "https://twitter.com/BikiniFinance",
    telegramUrl: "https://t.me/BikiniFinance",
    launchPrice: 1,
    toBeConfirmed: true,
  },
  {
    id: "5table",
    address: "0xe015236b280883b9fe316636B753b3FdefD13A08",
    address1: "0xe015236b280883b9fe316636B753b3FdefD13A08",
    address2: "0xe015236b280883b9fe316636B753b3FdefD13A08",
    isActive: false,
    name: "5table.finance",
    subTitle:
      "5table Finance is an advanced multichain, decentralized protocol that will allow you to find the best investment opportunities for your stable coins (DAI, USDT, USDC, BUSD and UST) in order to protect your invested capital, obtaining the best profitability that the market can offer, in a safe and sustainable platform.",
    description:
      "5table Finance is an advanced multichain, decentralized protocol that will allow you to find the best investment opportunities for your stable coins (DAI, USDT, USDC, BUSD and UST) in order to protect your invested capital, obtaining the best profitability that the market can offer, in a safe and sustainable platform.",
    launchDate: "November 30th",
    launchTime: "11PM UTC",
    saleAmount: "50,000 STABLE",
    raiseAmount: "200 WBNB",
    cakeToBurn: "0",
    projectSiteUrl: "",
    currency: "BUSD",
    currencyAddress: contracts.busd[56],
    tokenDecimals: 18,
    tokenSymbol: "STABLE",
    releaseBlockNumber: 5294924,
    campaignId: "007",
    twitterUrl: "https://twitter.com/5table_finance",
    telegramUrl: "https://t.me/S_table",
    mediumUrl: "https://5table.medium.com/",
    launchPrice: 1,
    toBeConfirmed: true,
  },
];

export default ifos;
